Update SyncConvertMerge-3R$-LE-3.yml

diff --git a/.github/workflows/SyncConvertMerge-3R$-LE-3.yml b/.github/workflows/SyncConvertMerge-3R$-LE-3.yml
--- a/.github/workflows/SyncConvertMerge-3R$-LE-3.yml
+++ b/.github/workflows/SyncConvertMerge-3R$-LE-3.yml
@@ -438,16 +438,17 @@ jobs:
       - name: Process, Deduplicate, Format and Merge Playlists
         shell: bash
         run: |
+          set +e # ensures we see all debug echos even on minor command failures
           TOTAL_GROUP_FAILURES=0 # tracks global failures across the clean and merge processes of all merged playlists, starts from 0
           PLAYLIST_METADATA="${{ github.workspace }}/remote_timestamps.meta"
           touch ./merged_files_to_commit.txt # creates a registry file to track successfully created merged playlists for the commit step
 
           # Step 1: Use helper function for group-wise cleaning and merging
           process_group() { # function encapsulating cleaning and merging processes for any given merged playlist folder
-            local dir="$1"
-            local output="$2"
+            local dir="$1" # parent folder (e.g., sl-le)
+            local output="$2" # target merged file (e.g., sl-le-all.m3u)
             shift 2
-            local sources=("$@")
+            local sources=("$@") # array of input playlists "m3u/filename.m3u"
             
             echo "-----------------------------------------------------------------------------"
             echo "PROCESS START: Creation of merged playlist $output in folder $dir"
@@ -459,22 +460,23 @@ jobs:
             local cleaned_details="" # record of file-size and count of #EXTINF lines in successfully cleaned input playlists, starts blank
 
             for src in "${sources[@]}"; do
-              local src_path="download-branch/$dir/$src"
+              local src_path="download-branch/$dir/$src" # constructs absolute path for input playlists e.g., download-branch/sl-le/m3u/sl-le-1.m3u
+              local filename=$(basename "$src") # e.g., filename sl-le-1.m3u extracted from src m3u/sl-le-1.m3u 
 
               # module: skip the input playlist if missing in download repo
               if [ ! -f "$src_path" ]; then # if input playlist is missing in download repo, skip it
                 echo "SKIPPED: Playlist $src not found in repository. Skipping file."
                 continue
-              fi
+              fi 
 
               # module: for input playlist in download repo, fetch remote timestamp (from file system) and time-note (from consolidated metadata file)
               local f_time=$(TZ='Asia/Kolkata' date -r "$src_path" "+%d-%m-%Y %H:%M IST") # pulls the remote timestamp already touched onto the input playlist by Job 1 or Job 2 of this workflow
-              local f_note=$(grep "|$src|" "$PLAYLIST_METADATA" | cut -d'|' -f6 || echo "") # extracts the time note for the input playlist from the metadata file
+              local f_note=$(grep "|$filename|" "$PLAYLIST_METADATA" | cut -d'|' -f6 || echo "") # extracts the time note for the input playlist from the metadata file
               [ -z "$f_note" ] && f_note="([x]m3u commit time)" # sets the playlist's time note if the same is not available from metadata file
               local LAST_MOD="$f_time $f_note" # combines remote timestamp and time note
 
               # module: clean input playlist (remove carriage returns and BOM) and echo its success/failure metrics
-              if (set -e; sed -i '1s/^\xef\xbb\xbf//; s/\r//g' "$src_path"); then # strips Windows line endings (\r) and any non-standard character markers
+              if sed -i '1s/^\xef\xbb\xbf//; s/\r//g' "$src_path" 2>/dev/null; then # strips Windows line endings (\r) and any non-standard character markers
                 successful_san_count=$((successful_san_count + 1))
                 local file_size=$(stat -c%s "$src_path") # file size in bytes of the cleaned input playlist
                 local extinf_count=$(grep -c "#EXTINF" "$src_path" || true) # count of #EXTINF lines present in the cleaned input playlist
@@ -502,7 +504,7 @@ jobs:
               set -e # ensures that subshell exits on critical command failure
               local target_dir="merge-branch/$dir"
               mkdir -p "$target_dir"
-              local target="$target_dir/$output"
+              local target="$target_dir/$output" # e.g., merge-branch/sl-le/sl-le-all.m3u
               local TRACKER="/tmp/seen_${output}_$(date +%s).tmp" # creates a unique temp tracker for this group's deduplication
 
               # module: initialize merged playlist
@@ -514,16 +516,17 @@ jobs:
               local block_index=0 # block_index tracks which source m3u-block we are currently writing to
               for src in "${sources[@]}"; do
                 local src_path="download-branch/$dir/$src"
+                local filename=$(basename "$src")
                 [ ! -f "$src_path" ] && continue
 
                 # sub-module: re-fetch timestamps for the block header (identical logic to cleaning stage)
                 local b_time=$(TZ='Asia/Kolkata' date -r "$src_path" "+%d-%m-%Y %H:%M IST")
-                local b_note=$(grep "|$src|" "$PLAYLIST_METADATA" | cut -d'|' -f6 || echo "")
+                local b_note=$(grep "|$filename|" "$PLAYLIST_METADATA" | cut -d'|' -f6 || echo "")
                 [ -z "$b_note" ] && b_note="([x]m3u commit time)"
                 local BLOCK_MOD="$b_time $b_note" 
 
                 # sub-module: awk function for deduplication and custom formatting
-                awk -v src_name="$src" -v tracker="$TRACKER" -v idx="$block_index" -v mod_date="$BLOCK_MOD" -v s=$RANDOM '
+                awk -v src_name="$filename" -v tracker="$TRACKER" -v idx="$block_index" -v mod_date="$BLOCK_MOD" -v s=$RANDOM '
 
                   # pre-processing
                   BEGIN {
@@ -534,7 +537,7 @@ jobs:
                     }
                     srand(s) # random mumber generator (for use in randomizing dummy ip address in printf later)
                   } 
-
+    
                   # deduplication
                   /^#EXTINF/ { found_stream=1 } # found_stream: 1 when the first #EXTINF line in the input playlist is found
                   {
@@ -559,13 +562,13 @@ jobs:
                       prefix = (idx == 0) ? "" : "\n\n" # if not the first block, prepends 2 empty lines
                       printf "%s# Playlist from %s : %d stream(s) \n", prefix, src_name, count # adds source identifier header
                       printf "# [last updated %s] \n\n", mod_date # adds remote update timestamp for the source playlist + 1-line trail spacing + content
-                      printf "#EXTINF:-1 tvg-id=\"\" tvg-name=\"\" tvg-logo=\"\" group-title=\"\",----●★ %s %s ★●----\n", src_name, mod_date # adds block divider
+                      printf "#EXTINF:-1,----●★ %s %s ★●----\n", src_name, mod_date # adds block divider
                       printf "http://%d.%d.%d.%d/%08d\n%s", rand()*256, rand()*256, rand()*256, rand()*256, rand()*10^8, file_buf # adds random dummy url for block divider
                     }
                   }                 
                 ' "$src_path" >> "$target" # appends input playlists to the merged playlist using the awk logic
 
-                if grep -q "Playlist from $src" "$target"; then # only increment block_index if this block was successfully added to the target
+                if grep -q "Playlist from $filename" "$target"; then # only increment block_index if this block was successfully added to the target
                    block_index=$((block_index + 1))
                 fi        
                 echo "Stream URLs from $src deduplicated and appended. $output now has $(wc -l < "$TRACKER") unique stream URLs."
@@ -588,7 +591,7 @@ jobs:
             fi
           }
 
-          # Step 2: Dynamic execution loop (using indirect expansion) for playlist groups
+          # Step 2: Dynamic discovery and execution loop (using indirect expansion) for playlist groups
           DIRS=$(cut -d'|' -f1 "$PLAYLIST_METADATA" | sed 's|\(.*\)/.*|\1|' | sort -u) # extracts all unique directories in the consolidated metadata file
           for DIR in $DIRS; do # maps the identified directories to merged playlist names
               VAR_SUFFIX=$(echo "$DIR" | tr '-' '_') # creates suffix for the lookup variable from directory name (e.g., sl-le -> sl_le)
@@ -599,14 +602,22 @@ jobs:
                 continue
               fi
 
-              # Sub-step 2a: Identify active folder groups (touched by Job 1 and so present in metadata file), pick all M3Us present in the active folder (new + pre-existing)
-              mapfile -t FILES_FOR_GROUP < <(find "download-branch/$DIR" -mindepth 1 -name "*.m3u" ! -name "$OUTPUT_NAME" -exec basename {} \;) # for merge process, picks only those folders in download-branch that are present in timestamps metadata file
+              # Sub-step 2a: Identify active folder groups (touched by Job 1 and so present in metadata file), then pick all input playlists present in the m3u sub-folder (new + pre-existing)
+              if [ -d "download-branch/$DIR/m3u" ]; then # checks if the identified directory (from the metadata file) in the download-branch has a 'm3u' sub-folder 
+                # %f returns just the name; we manually prepend 'm3u/' so process_group knows where to look
+                mapfile -t FILES_FOR_GROUP < <(find "download-branch/$DIR/m3u" -maxdepth 1 -name "*.m3u" ! -name "$OUTPUT_NAME" -printf "m3u/%f\n" | sort) # for merge process, picks only those folders in download-branch that are present in timestamps metadata file; checks ONLY the 'm3u' subfolder within the parent group and assigns the input playlists within the sub-folder to $OUTPUT_NAME
+              fi           
+
+              # Sub-step 2b: Call the process_group function for found input playlists
               if [ ${#FILES_FOR_GROUP[@]} -gt 0 ]; then # checks if any input playlists for this group were actually found
+                  echo "DEBUG: Found ${#FILES_FOR_GROUP[@]} input M3U playlists in $DIR/m3u subfolder."
                   if process_group "$DIR" "$OUTPUT_NAME" "${FILES_FOR_GROUP[@]}"; then # calls the 'process_group' function with the dynamic folder, merged playlist name, and input playlist array
                       echo "$DIR/$OUTPUT_NAME" >> ./merged_files_to_commit.txt # registers the successfully merged playlist for the commit step
                   else
                       TOTAL_GROUP_FAILURES=$((TOTAL_GROUP_FAILURES + 1)) # increments the global error counter everytime the merge function fails 
                   fi
+              else
+                  echo "DEBUG: No input M3U playlists found in $DIR/m3u subfolder."
               fi
           done             
           
